{% set name = "diffpy.pdfmorph" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/diffpy/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 21e49694f7317697e91f26407accae56b4cd8847eadea09ab6c77c6e17116296

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - pdfmorph = diffpy.pdfmorph.pdfmorphapp:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - matplotlib-base
    - diffpy.utils
    - scipy
    - numpy
    - bg-mpl-stylesheets
    - python >=3

test:
  imports:
    - diffpy.pdfmorph

about:
  home: http://github.com/diffpy/diffpy.pdfmorph
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'More quantitative measurements and analyses for spectra taken at different temperatures.'

  description: |
    PDFmorph is a Python software package designed to increase the insight
    researchers can get into their spectra collected for atomic pair 
    distribution functions
  # doc_url: doc_url to be released in a later version.
  dev_url: https://github.com/diffpy/diffpy.pdfmorph

extra:
  recipe-maintainers:
    - bobleesj
    - chiahaoliu
    - CJ-Wright
    - pavoljuhas
    - sbillinge
